/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-utf-8.js']) {
  _$jscoverage['javascript-utf-8.js'] = [];
  _$jscoverage['javascript-utf-8.js'][1] = 0;
  _$jscoverage['javascript-utf-8.js'][2] = 0;
}
_$jscoverage['javascript-utf-8.js'][1]++;
var s = "e\u00e8\u00e9\u00ea";
_$jscoverage['javascript-utf-8.js'][2]++;
var r = /e\u00e8\u00e9\u00ea/;
_$jscoverage['javascript-utf-8.js'].source = ["<span class=\"k\">var</span> s <span class=\"k\">=</span> <span class=\"s\">'e&#232;&#233;&#234;'</span><span class=\"k\">;</span>","<span class=\"k\">var</span> r <span class=\"k\">=</span> <span class=\"s\">/e&#232;&#233;&#234;/</span><span class=\"k\">;</span>"];
