/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-inc.js']) {
  _$jscoverage['javascript-inc.js'] = [];
  _$jscoverage['javascript-inc.js'][1] = 0;
  _$jscoverage['javascript-inc.js'][2] = 0;
}
_$jscoverage['javascript-inc.js'][1]++;
x++;
_$jscoverage['javascript-inc.js'][2]++;
++x;

// x++;
// ++x;
