/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-switch.js']) {
  _$jscoverage['javascript-switch.js'] = [];
  _$jscoverage['javascript-switch.js'][1] = 0;
  _$jscoverage['javascript-switch.js'][3] = 0;
  _$jscoverage['javascript-switch.js'][4] = 0;
  _$jscoverage['javascript-switch.js'][6] = 0;
  _$jscoverage['javascript-switch.js'][7] = 0;
  _$jscoverage['javascript-switch.js'][8] = 0;
  _$jscoverage['javascript-switch.js'][10] = 0;
  _$jscoverage['javascript-switch.js'][11] = 0;
  _$jscoverage['javascript-switch.js'][14] = 0;
  _$jscoverage['javascript-switch.js'][16] = 0;
  _$jscoverage['javascript-switch.js'][17] = 0;
  _$jscoverage['javascript-switch.js'][18] = 0;
  _$jscoverage['javascript-switch.js'][20] = 0;
}
_$jscoverage['javascript-switch.js'].source = ["<span class=\"k\">switch</span> <span class=\"k\">(</span>x<span class=\"k\">)</span> <span class=\"k\">{</span>","<span class=\"k\">case</span> x<span class=\"k\">:</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","  <span class=\"k\">break</span><span class=\"k\">;</span>","<span class=\"k\">case</span> y<span class=\"k\">:</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","  y <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","  <span class=\"k\">break</span><span class=\"k\">;</span>","<span class=\"k\">default</span><span class=\"k\">:</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","  <span class=\"k\">break</span><span class=\"k\">;</span>","<span class=\"k\">}</span>","","<span class=\"k\">switch</span> <span class=\"k\">(</span>x<span class=\"k\">)</span> <span class=\"k\">{</span>","<span class=\"k\">case</span> <span class=\"s\">1</span><span class=\"k\">:</span>","  <span class=\"k\">let</span> y <span class=\"k\">=</span> <span class=\"s\">1</span><span class=\"k\">;</span>","  f<span class=\"k\">(</span>y<span class=\"k\">);</span>","  <span class=\"k\">break</span><span class=\"k\">;</span>","<span class=\"k\">case</span> <span class=\"s\">2</span><span class=\"k\">:</span>","  <span class=\"k\">break</span><span class=\"k\">;</span>","<span class=\"k\">}</span>"];
_$jscoverage['javascript-switch.js'][1]++;
switch (x) {
case x:
  _$jscoverage['javascript-switch.js'][3]++;
  x = 0;
  _$jscoverage['javascript-switch.js'][4]++;
  break;
case y:
  _$jscoverage['javascript-switch.js'][6]++;
  x = 0;
  _$jscoverage['javascript-switch.js'][7]++;
  y = 0;
  _$jscoverage['javascript-switch.js'][8]++;
  break;
default:
  _$jscoverage['javascript-switch.js'][10]++;
  x = 0;
  _$jscoverage['javascript-switch.js'][11]++;
  break;
}
_$jscoverage['javascript-switch.js'][14]++;
switch (x) {
case 1:
  _$jscoverage['javascript-switch.js'][16]++;
  let y = 1;
  _$jscoverage['javascript-switch.js'][17]++;
  f(y);
  _$jscoverage['javascript-switch.js'][18]++;
  break;
case 2:
  _$jscoverage['javascript-switch.js'][20]++;
  break;
}
