/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-string.js']) {
  _$jscoverage['javascript-string.js'] = [];
  _$jscoverage['javascript-string.js'][1] = 0;
  _$jscoverage['javascript-string.js'][2] = 0;
  _$jscoverage['javascript-string.js'][3] = 0;
  _$jscoverage['javascript-string.js'][4] = 0;
  _$jscoverage['javascript-string.js'][5] = 0;
  _$jscoverage['javascript-string.js'][6] = 0;
  _$jscoverage['javascript-string.js'][7] = 0;
  _$jscoverage['javascript-string.js'][8] = 0;
  _$jscoverage['javascript-string.js'][10] = 0;
}
_$jscoverage['javascript-string.js'].source = ["x <span class=\"k\">=</span> <span class=\"s\">\"\"</span><span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"s\">''</span><span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"s\">\"x\"</span><span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"s\">'x'</span><span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"s\">\"</span><span class=\"t\">\\\"</span><span class=\"s\">\"</span><span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"s\">'</span><span class=\"t\">\\'</span><span class=\"s\">'</span><span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"s\">\"</span><span class=\"t\">\\b\\t\\n\\v\\f\\r\\\"\\'\\\\</span><span class=\"s\">\"</span><span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> RegExp<span class=\"k\">(</span><span class=\"s\">'x</span><span class=\"t\">\\\\</span><span class=\"s\">(</span><span class=\"t\">\\\\</span><span class=\"s\">)</span><span class=\"t\">\\\\\\\\\\\\</span><span class=\"s\">/'</span><span class=\"k\">);</span>","","x <span class=\"k\">=</span> <span class=\"s\">'foo</span><span class=\"t\">\\</span>","<span class=\"s\">bar'</span><span class=\"k\">;</span>"];
_$jscoverage['javascript-string.js'][1]++;
x = "";
_$jscoverage['javascript-string.js'][2]++;
x = "";
_$jscoverage['javascript-string.js'][3]++;
x = "x";
_$jscoverage['javascript-string.js'][4]++;
x = "x";
_$jscoverage['javascript-string.js'][5]++;
x = "\"";
_$jscoverage['javascript-string.js'][6]++;
x = "'";
_$jscoverage['javascript-string.js'][7]++;
x = "\b\t\n\u000b\f\r\"'\\";
_$jscoverage['javascript-string.js'][8]++;
x = new RegExp("x\\(\\)\\\\\\/");
_$jscoverage['javascript-string.js'][10]++;
x = "foobar";
