/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-hook.js']) {
  _$jscoverage['javascript-hook.js'] = [];
  _$jscoverage['javascript-hook.js'][1] = 0;
  _$jscoverage['javascript-hook.js'][2] = 0;
}
_$jscoverage['javascript-hook.js'].source = ["<span class=\"k\">var</span> x <span class=\"k\">=</span> <span class=\"s\">1</span><span class=\"k\">;</span>","<span class=\"k\">var</span> y <span class=\"k\">=</span> x <span class=\"k\">===</span> <span class=\"s\">1</span><span class=\"k\">?</span> <span class=\"s\">\"x\"</span><span class=\"k\">:</span> <span class=\"s\">\"y\"</span><span class=\"k\">;</span>"];
_$jscoverage['javascript-hook.js'][1]++;
var x = 1;
_$jscoverage['javascript-hook.js'][2]++;
var y = ((x === 1)? "x": "y");
