/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-with.js']) {
  _$jscoverage['javascript-with.js'] = [];
  _$jscoverage['javascript-with.js'][1] = 0;
  _$jscoverage['javascript-with.js'][2] = 0;
  _$jscoverage['javascript-with.js'][4] = 0;
  _$jscoverage['javascript-with.js'][5] = 0;
  _$jscoverage['javascript-with.js'][8] = 0;
  _$jscoverage['javascript-with.js'][9] = 0;
}
_$jscoverage['javascript-with.js'].source = ["<span class=\"k\">function</span> f<span class=\"k\">()</span> <span class=\"k\">{}</span>","<span class=\"k\">var</span> x <span class=\"k\">=</span> <span class=\"k\">{}</span><span class=\"k\">;</span>","","<span class=\"k\">with</span> <span class=\"k\">(</span>x<span class=\"k\">)</span> <span class=\"k\">{</span>","  f<span class=\"k\">();</span>","<span class=\"k\">}</span>","","<span class=\"k\">with</span> <span class=\"k\">(</span>x<span class=\"k\">)</span>","  f<span class=\"k\">();</span>"];
_$jscoverage['javascript-with.js'][1]++;
function f() {
}
_$jscoverage['javascript-with.js'][2]++;
var x = {};
_$jscoverage['javascript-with.js'][4]++;
with (x) {
  _$jscoverage['javascript-with.js'][5]++;
  f();
}
_$jscoverage['javascript-with.js'][8]++;
with (x) {
  _$jscoverage['javascript-with.js'][9]++;
  f();
}
