/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-try.js']) {
  _$jscoverage['javascript-try.js'] = [];
  _$jscoverage['javascript-try.js'][1] = 0;
  _$jscoverage['javascript-try.js'][3] = 0;
  _$jscoverage['javascript-try.js'][4] = 0;
  _$jscoverage['javascript-try.js'][7] = 0;
  _$jscoverage['javascript-try.js'][10] = 0;
  _$jscoverage['javascript-try.js'][11] = 0;
  _$jscoverage['javascript-try.js'][14] = 0;
  _$jscoverage['javascript-try.js'][17] = 0;
  _$jscoverage['javascript-try.js'][18] = 0;
  _$jscoverage['javascript-try.js'][21] = 0;
  _$jscoverage['javascript-try.js'][24] = 0;
  _$jscoverage['javascript-try.js'][25] = 0;
  _$jscoverage['javascript-try.js'][28] = 0;
  _$jscoverage['javascript-try.js'][31] = 0;
}
_$jscoverage['javascript-try.js'].source = ["<span class=\"k\">function</span> f<span class=\"k\">()</span> <span class=\"k\">{}</span>","","<span class=\"k\">try</span> <span class=\"k\">{</span>","  f<span class=\"k\">();</span>","<span class=\"k\">}</span>","<span class=\"k\">catch</span> <span class=\"k\">(</span>e<span class=\"k\">)</span> <span class=\"k\">{</span>","  f<span class=\"k\">();</span>","<span class=\"k\">}</span>","","<span class=\"k\">try</span> <span class=\"k\">{</span>","  f<span class=\"k\">();</span>","<span class=\"k\">}</span>","<span class=\"k\">catch</span> <span class=\"k\">(</span>e <span class=\"k\">if</span> e <span class=\"k\">instanceof</span> E<span class=\"k\">)</span> <span class=\"k\">{</span>","  f<span class=\"k\">();</span>","<span class=\"k\">}</span>","","<span class=\"k\">try</span> <span class=\"k\">{</span>","  f<span class=\"k\">();</span>","<span class=\"k\">}</span>","<span class=\"k\">finally</span> <span class=\"k\">{</span>","  f<span class=\"k\">();</span>","<span class=\"k\">}</span>","","<span class=\"k\">try</span> <span class=\"k\">{</span>","  f<span class=\"k\">();</span>","<span class=\"k\">}</span>","<span class=\"k\">catch</span> <span class=\"k\">(</span>e<span class=\"k\">)</span> <span class=\"k\">{</span>","  f<span class=\"k\">();</span>","<span class=\"k\">}</span>","<span class=\"k\">finally</span> <span class=\"k\">{</span>","  f<span class=\"k\">();</span>","<span class=\"k\">}</span>"];
_$jscoverage['javascript-try.js'][1]++;
function f() {
}
_$jscoverage['javascript-try.js'][3]++;
try {
  _$jscoverage['javascript-try.js'][4]++;
  f();
}
catch (e) {
  _$jscoverage['javascript-try.js'][7]++;
  f();
}
_$jscoverage['javascript-try.js'][10]++;
try {
  _$jscoverage['javascript-try.js'][11]++;
  f();
}
catch (e if (e instanceof E)) {
  _$jscoverage['javascript-try.js'][14]++;
  f();
}
_$jscoverage['javascript-try.js'][17]++;
try {
  _$jscoverage['javascript-try.js'][18]++;
  f();
}
finally {
  _$jscoverage['javascript-try.js'][21]++;
  f();
}
_$jscoverage['javascript-try.js'][24]++;
try {
  _$jscoverage['javascript-try.js'][25]++;
  f();
}
catch (e) {
  _$jscoverage['javascript-try.js'][28]++;
  f();
}
finally {
  _$jscoverage['javascript-try.js'][31]++;
  f();
}
