/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-dot.js']) {
  _$jscoverage['javascript-dot.js'] = [];
  _$jscoverage['javascript-dot.js'][1] = 0;
  _$jscoverage['javascript-dot.js'][2] = 0;
  _$jscoverage['javascript-dot.js'][3] = 0;
  _$jscoverage['javascript-dot.js'][4] = 0;
  _$jscoverage['javascript-dot.js'][5] = 0;
  _$jscoverage['javascript-dot.js'][7] = 0;
  _$jscoverage['javascript-dot.js'][8] = 0;
}
_$jscoverage['javascript-dot.js'].source = ["x<span class=\"k\">.</span>y <span class=\"k\">=</span> y<span class=\"k\">.</span>x<span class=\"k\">;</span>","x<span class=\"k\">[</span><span class=\"s\">\"y\"</span><span class=\"k\">]</span> <span class=\"k\">=</span> y<span class=\"k\">[</span><span class=\"s\">\"x\"</span><span class=\"k\">];</span>","x<span class=\"k\">[</span>y<span class=\"k\">]</span> <span class=\"k\">=</span> y<span class=\"k\">[</span>x<span class=\"k\">];</span>","x<span class=\"k\">[</span><span class=\"s\">'2y'</span><span class=\"k\">]</span> <span class=\"k\">=</span> y<span class=\"k\">[</span><span class=\"s\">'var'</span><span class=\"k\">];</span>","x<span class=\"k\">[</span><span class=\"s\">''</span><span class=\"k\">]</span> <span class=\"k\">=</span> y<span class=\"k\">[</span><span class=\"s\">\"\"</span><span class=\"k\">];</span>","","print<span class=\"k\">(</span><span class=\"s\">123.0</span><span class=\"k\">.</span>toString<span class=\"k\">());</span>","<span class=\"k\">(</span><span class=\"k\">{}</span><span class=\"k\">.</span>toString<span class=\"k\">());</span>"];
_$jscoverage['javascript-dot.js'][1]++;
x.y = y.x;
_$jscoverage['javascript-dot.js'][2]++;
x.y = y.x;
_$jscoverage['javascript-dot.js'][3]++;
x[y] = y[x];
_$jscoverage['javascript-dot.js'][4]++;
x["2y"] = y["var"];
_$jscoverage['javascript-dot.js'][5]++;
x[""] = y[""];
_$jscoverage['javascript-dot.js'][7]++;
print((123).toString());
_$jscoverage['javascript-dot.js'][8]++;
({}).toString();
