/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-if.js']) {
  _$jscoverage['javascript-if.js'] = [];
  _$jscoverage['javascript-if.js'][1] = 0;
  _$jscoverage['javascript-if.js'][3] = 0;
  _$jscoverage['javascript-if.js'][4] = 0;
  _$jscoverage['javascript-if.js'][6] = 0;
  _$jscoverage['javascript-if.js'][7] = 0;
  _$jscoverage['javascript-if.js'][10] = 0;
  _$jscoverage['javascript-if.js'][11] = 0;
  _$jscoverage['javascript-if.js'][13] = 0;
  _$jscoverage['javascript-if.js'][15] = 0;
  _$jscoverage['javascript-if.js'][16] = 0;
  _$jscoverage['javascript-if.js'][19] = 0;
  _$jscoverage['javascript-if.js'][22] = 0;
  _$jscoverage['javascript-if.js'][23] = 0;
  _$jscoverage['javascript-if.js'][25] = 0;
  _$jscoverage['javascript-if.js'][26] = 0;
  _$jscoverage['javascript-if.js'][29] = 0;
}
_$jscoverage['javascript-if.js'].source = ["<span class=\"k\">var</span> x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","","<span class=\"k\">if</span> <span class=\"k\">(</span>x<span class=\"k\">)</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","","<span class=\"k\">if</span> <span class=\"k\">(</span>x<span class=\"k\">)</span> <span class=\"k\">{</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","<span class=\"k\">}</span>","","<span class=\"k\">if</span> <span class=\"k\">(</span>x<span class=\"k\">)</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","<span class=\"k\">else</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","","<span class=\"k\">if</span> <span class=\"k\">(</span>x<span class=\"k\">)</span> <span class=\"k\">{</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","<span class=\"k\">}</span>","<span class=\"k\">else</span> <span class=\"k\">{</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","<span class=\"k\">}</span>","","<span class=\"k\">if</span> <span class=\"k\">(</span>x<span class=\"k\">)</span> <span class=\"k\">{</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","<span class=\"k\">}</span>","<span class=\"k\">else</span> <span class=\"k\">if</span> <span class=\"k\">(</span>x<span class=\"k\">)</span> <span class=\"k\">{</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","<span class=\"k\">}</span>","<span class=\"k\">else</span> <span class=\"k\">{</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","<span class=\"k\">}</span>"];
_$jscoverage['javascript-if.js'][1]++;
var x = 0;
_$jscoverage['javascript-if.js'][3]++;
if (x) {
  _$jscoverage['javascript-if.js'][4]++;
  x = 0;
}
_$jscoverage['javascript-if.js'][6]++;
if (x) {
  _$jscoverage['javascript-if.js'][7]++;
  x = 0;
}
_$jscoverage['javascript-if.js'][10]++;
if (x) {
  _$jscoverage['javascript-if.js'][11]++;
  x = 0;
}
else {
  _$jscoverage['javascript-if.js'][13]++;
  x = 0;
}
_$jscoverage['javascript-if.js'][15]++;
if (x) {
  _$jscoverage['javascript-if.js'][16]++;
  x = 0;
}
else {
  _$jscoverage['javascript-if.js'][19]++;
  x = 0;
}
_$jscoverage['javascript-if.js'][22]++;
if (x) {
  _$jscoverage['javascript-if.js'][23]++;
  x = 0;
}
else {
  _$jscoverage['javascript-if.js'][25]++;
  if (x) {
    _$jscoverage['javascript-if.js'][26]++;
    x = 0;
  }
  else {
    _$jscoverage['javascript-if.js'][29]++;
    x = 0;
  }
}
