/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-do.js']) {
  _$jscoverage['javascript-do.js'] = [];
  _$jscoverage['javascript-do.js'][1] = 0;
  _$jscoverage['javascript-do.js'][3] = 0;
  _$jscoverage['javascript-do.js'][4] = 0;
  _$jscoverage['javascript-do.js'][8] = 0;
  _$jscoverage['javascript-do.js'][9] = 0;
}
_$jscoverage['javascript-do.js'].source = ["<span class=\"k\">var</span> x<span class=\"k\">;</span>","","<span class=\"k\">do</span> <span class=\"k\">{</span>","  x <span class=\"k\">=</span> <span class=\"k\">false</span><span class=\"k\">;</span>","<span class=\"k\">}</span>","<span class=\"k\">while</span> <span class=\"k\">(</span>x<span class=\"k\">);</span>","","<span class=\"k\">do</span>","  x <span class=\"k\">=</span> <span class=\"k\">false</span><span class=\"k\">;</span>","<span class=\"k\">while</span> <span class=\"k\">(</span>x<span class=\"k\">);</span>"];
_$jscoverage['javascript-do.js'][1]++;
var x;
_$jscoverage['javascript-do.js'][3]++;
do {
  _$jscoverage['javascript-do.js'][4]++;
  x = false;
}
while (x);
_$jscoverage['javascript-do.js'][8]++;
do {
  _$jscoverage['javascript-do.js'][9]++;
  x = false;
}
while (x);
