/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-rc.js']) {
  _$jscoverage['javascript-rc.js'] = [];
  _$jscoverage['javascript-rc.js'][1] = 0;
  _$jscoverage['javascript-rc.js'][4] = 0;
}
_$jscoverage['javascript-rc.js'][1]++;
x = {x: y};
_$jscoverage['javascript-rc.js'][4]++;
x = {x: y, y: x};

// x = {
//   x: y
// };
// x = {
//   x: y,
//   y: x
// };
