/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-assign.js']) {
  _$jscoverage['javascript-assign.js'] = [];
  _$jscoverage['javascript-assign.js'][1] = 0;
  _$jscoverage['javascript-assign.js'][2] = 0;
  _$jscoverage['javascript-assign.js'][3] = 0;
  _$jscoverage['javascript-assign.js'][4] = 0;
  _$jscoverage['javascript-assign.js'][5] = 0;
  _$jscoverage['javascript-assign.js'][6] = 0;
  _$jscoverage['javascript-assign.js'][7] = 0;
  _$jscoverage['javascript-assign.js'][8] = 0;
  _$jscoverage['javascript-assign.js'][9] = 0;
  _$jscoverage['javascript-assign.js'][10] = 0;
  _$jscoverage['javascript-assign.js'][11] = 0;
  _$jscoverage['javascript-assign.js'][12] = 0;
}
_$jscoverage['javascript-assign.js'][1]++;
x = y;
_$jscoverage['javascript-assign.js'][2]++;
x += y;
_$jscoverage['javascript-assign.js'][3]++;
x -= y;
_$jscoverage['javascript-assign.js'][4]++;
x *= y;
_$jscoverage['javascript-assign.js'][5]++;
x %= y;
_$jscoverage['javascript-assign.js'][6]++;
x <<= y;
_$jscoverage['javascript-assign.js'][7]++;
x >>= y;
_$jscoverage['javascript-assign.js'][8]++;
x >>>= y;
_$jscoverage['javascript-assign.js'][9]++;
x &= y;
_$jscoverage['javascript-assign.js'][10]++;
x |= y;
_$jscoverage['javascript-assign.js'][11]++;
x ^= y;
_$jscoverage['javascript-assign.js'][12]++;
x /= y;
