/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-switch.js']) {
  _$jscoverage['javascript-switch.js'] = [];
  _$jscoverage['javascript-switch.js'][1] = 0;
  _$jscoverage['javascript-switch.js'][3] = 0;
  _$jscoverage['javascript-switch.js'][4] = 0;
  _$jscoverage['javascript-switch.js'][6] = 0;
  _$jscoverage['javascript-switch.js'][7] = 0;
  _$jscoverage['javascript-switch.js'][8] = 0;
  _$jscoverage['javascript-switch.js'][10] = 0;
  _$jscoverage['javascript-switch.js'][11] = 0;
}
_$jscoverage['javascript-switch.js'][1]++;
switch (x) {
case x:
  _$jscoverage['javascript-switch.js'][3]++;
  x = 0;
  _$jscoverage['javascript-switch.js'][4]++;
  break;
case y:
  _$jscoverage['javascript-switch.js'][6]++;
  x = 0;
  _$jscoverage['javascript-switch.js'][7]++;
  y = 0;
  _$jscoverage['javascript-switch.js'][8]++;
  break;
default:
  _$jscoverage['javascript-switch.js'][10]++;
  x = 0;
  _$jscoverage['javascript-switch.js'][11]++;
  break;
}
_$jscoverage['javascript-switch.js'].source = ["<span class=\"k\">switch</span> <span class=\"k\">(</span>x<span class=\"k\">)</span> <span class=\"k\">{</span>","<span class=\"k\">case</span> x<span class=\"k\">:</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","  <span class=\"k\">break</span><span class=\"k\">;</span>","<span class=\"k\">case</span> y<span class=\"k\">:</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","  y <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","  <span class=\"k\">break</span><span class=\"k\">;</span>","<span class=\"k\">default</span><span class=\"k\">:</span>","  x <span class=\"k\">=</span> <span class=\"s\">0</span><span class=\"k\">;</span>","  <span class=\"k\">break</span><span class=\"k\">;</span>","<span class=\"k\">}</span>"];
