/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-object.js']) {
  _$jscoverage['javascript-object.js'] = [];
  _$jscoverage['javascript-object.js'][1] = 0;
}
_$jscoverage['javascript-object.js'][1]++;
x = /x\(\)\\\//i;
