/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-foreach.js']) {
  _$jscoverage['javascript-foreach.js'] = [];
  _$jscoverage['javascript-foreach.js'][6] = 0;
  _$jscoverage['javascript-foreach.js'][7] = 0;
}
_$jscoverage['javascript-foreach.js'].source = ["<span class=\"c\">/*</span>","<span class=\"c\">https://developer.mozilla.org/en/Core_JavaScript_1.5_Guide/Object_Manipulation_Statements</span>","<span class=\"c\">https://developer.mozilla.org/en/Core_JavaScript_1.5_Reference/Statements/for_each...in</span>","<span class=\"c\">*/</span>","","<span class=\"k\">for</span> each <span class=\"k\">(</span><span class=\"k\">var</span> item <span class=\"k\">in</span> obj<span class=\"k\">)</span> <span class=\"k\">{</span>","  sum <span class=\"k\">+=</span> item<span class=\"k\">;</span>","<span class=\"k\">}</span>"];
_$jscoverage['javascript-foreach.js'][6]++;
for each (var item in obj) {
  _$jscoverage['javascript-foreach.js'][7]++;
  sum += item;
}
