/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-number.js']) {
  _$jscoverage['javascript-number.js'] = [];
  _$jscoverage['javascript-number.js'][1] = 0;
  _$jscoverage['javascript-number.js'][2] = 0;
  _$jscoverage['javascript-number.js'][3] = 0;
  _$jscoverage['javascript-number.js'][5] = 0;
  _$jscoverage['javascript-number.js'][6] = 0;
}
_$jscoverage['javascript-number.js'][1]++;
x = 1;
_$jscoverage['javascript-number.js'][2]++;
y = 2;
_$jscoverage['javascript-number.js'][3]++;
z = 10.5;
_$jscoverage['javascript-number.js'][5]++;
a = Number.POSITIVE_INFINITY;
_$jscoverage['javascript-number.js'][6]++;
a = Number.NEGATIVE_INFINITY;
_$jscoverage['javascript-number.js'].source = ["x <span class=\"k\">=</span> <span class=\"s\">1</span><span class=\"k\">;</span>","y <span class=\"k\">=</span> <span class=\"s\">2</span><span class=\"k\">;</span>","z <span class=\"k\">=</span> <span class=\"s\">10.5</span><span class=\"k\">;</span>","","a <span class=\"k\">=</span> <span class=\"s\">1</span> <span class=\"k\">/</span> <span class=\"s\">0</span><span class=\"k\">;</span>","a <span class=\"k\">=</span> <span class=\"k\">-</span><span class=\"s\">1</span> <span class=\"k\">/</span> <span class=\"s\">0</span><span class=\"k\">;</span>"];
