/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-dot.js']) {
  _$jscoverage['javascript-dot.js'] = [];
  _$jscoverage['javascript-dot.js'][1] = 0;
  _$jscoverage['javascript-dot.js'][2] = 0;
  _$jscoverage['javascript-dot.js'][3] = 0;
  _$jscoverage['javascript-dot.js'][4] = 0;
  _$jscoverage['javascript-dot.js'][5] = 0;
}
_$jscoverage['javascript-dot.js'][1]++;
x.y = y.x;
_$jscoverage['javascript-dot.js'][2]++;
x.y = y.x;
_$jscoverage['javascript-dot.js'][3]++;
x[y] = y[x];
_$jscoverage['javascript-dot.js'][4]++;
x["2y"] = y["var"];
_$jscoverage['javascript-dot.js'][5]++;
x[""] = y[""];
_$jscoverage['javascript-dot.js'].source = ["x<span class=\"k\">.</span>y <span class=\"k\">=</span> y<span class=\"k\">.</span>x<span class=\"k\">;</span>","x<span class=\"k\">[</span><span class=\"s\">\"y\"</span><span class=\"k\">]</span> <span class=\"k\">=</span> y<span class=\"k\">[</span><span class=\"s\">\"x\"</span><span class=\"k\">];</span>","x<span class=\"k\">[</span>y<span class=\"k\">]</span> <span class=\"k\">=</span> y<span class=\"k\">[</span>x<span class=\"k\">];</span>","x<span class=\"k\">[</span><span class=\"s\">'2y'</span><span class=\"k\">]</span> <span class=\"k\">=</span> y<span class=\"k\">[</span><span class=\"s\">'var'</span><span class=\"k\">];</span>","x<span class=\"k\">[</span><span class=\"s\">''</span><span class=\"k\">]</span> <span class=\"k\">=</span> y<span class=\"k\">[</span><span class=\"s\">\"\"</span><span class=\"k\">];</span>"];
