/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-hook.js']) {
  _$jscoverage['javascript-hook.js'] = [];
  _$jscoverage['javascript-hook.js'][1] = 0;
  _$jscoverage['javascript-hook.js'][2] = 0;
}
_$jscoverage['javascript-hook.js'][1]++;
var x = 1;
_$jscoverage['javascript-hook.js'][2]++;
var y = x === 1? "x": "y";

// var x = 1;
// var y = x === 1? "x": "y";
