/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-with.js']) {
  _$jscoverage['javascript-with.js'] = [];
  _$jscoverage['javascript-with.js'][1] = 0;
  _$jscoverage['javascript-with.js'][2] = 0;
  _$jscoverage['javascript-with.js'][5] = 0;
  _$jscoverage['javascript-with.js'][6] = 0;
}
_$jscoverage['javascript-with.js'][1]++;
with (x) {
  _$jscoverage['javascript-with.js'][2]++;
  x();
}
_$jscoverage['javascript-with.js'][5]++;
with (x) {
  _$jscoverage['javascript-with.js'][6]++;
  x();
}
