/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-comma.js']) {
  _$jscoverage['javascript-comma.js'] = [];
  _$jscoverage['javascript-comma.js'][1] = 0;
}
_$jscoverage['javascript-comma.js'][1]++;
x = y, y = x;

// x = y, y = x;
