/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-unaryop.js']) {
  _$jscoverage['javascript-unaryop.js'] = [];
  _$jscoverage['javascript-unaryop.js'][1] = 0;
  _$jscoverage['javascript-unaryop.js'][2] = 0;
  _$jscoverage['javascript-unaryop.js'][3] = 0;
  _$jscoverage['javascript-unaryop.js'][4] = 0;
  _$jscoverage['javascript-unaryop.js'][5] = 0;
  _$jscoverage['javascript-unaryop.js'][6] = 0;
  _$jscoverage['javascript-unaryop.js'][7] = 0;
}
_$jscoverage['javascript-unaryop.js'].source = ["x <span class=\"k\">=</span> <span class=\"k\">-</span>x<span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"k\">+</span>x<span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"k\">!</span>x<span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"k\">~</span>x<span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"k\">typeof</span> x<span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"k\">typeof</span> <span class=\"s\">123</span><span class=\"k\">;</span>  <span class=\"c\">// this has a different pn_op value</span>","x <span class=\"k\">=</span> <span class=\"k\">void</span> x<span class=\"k\">;</span>"];
_$jscoverage['javascript-unaryop.js'][1]++;
x = (- x);
_$jscoverage['javascript-unaryop.js'][2]++;
x = (+ x);
_$jscoverage['javascript-unaryop.js'][3]++;
x = (! x);
_$jscoverage['javascript-unaryop.js'][4]++;
x = (~ x);
_$jscoverage['javascript-unaryop.js'][5]++;
x = (typeof x);
_$jscoverage['javascript-unaryop.js'][6]++;
x = (typeof 123);
_$jscoverage['javascript-unaryop.js'][7]++;
x = (void x);
