/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-if.js']) {
  _$jscoverage['javascript-if.js'] = [];
  _$jscoverage['javascript-if.js'][1] = 0;
  _$jscoverage['javascript-if.js'][2] = 0;
  _$jscoverage['javascript-if.js'][4] = 0;
  _$jscoverage['javascript-if.js'][5] = 0;
  _$jscoverage['javascript-if.js'][8] = 0;
  _$jscoverage['javascript-if.js'][9] = 0;
  _$jscoverage['javascript-if.js'][11] = 0;
  _$jscoverage['javascript-if.js'][13] = 0;
  _$jscoverage['javascript-if.js'][14] = 0;
  _$jscoverage['javascript-if.js'][17] = 0;
  _$jscoverage['javascript-if.js'][20] = 0;
  _$jscoverage['javascript-if.js'][21] = 0;
  _$jscoverage['javascript-if.js'][23] = 0;
  _$jscoverage['javascript-if.js'][24] = 0;
  _$jscoverage['javascript-if.js'][27] = 0;
}
_$jscoverage['javascript-if.js'][1]++;
if (x) {
  _$jscoverage['javascript-if.js'][2]++;
  x();
}
_$jscoverage['javascript-if.js'][4]++;
if (x) {
  _$jscoverage['javascript-if.js'][5]++;
  x();
}
_$jscoverage['javascript-if.js'][8]++;
if (x) {
  _$jscoverage['javascript-if.js'][9]++;
  x();
}
else {
  _$jscoverage['javascript-if.js'][11]++;
  x();
}
_$jscoverage['javascript-if.js'][13]++;
if (x) {
  _$jscoverage['javascript-if.js'][14]++;
  x();
}
else {
  _$jscoverage['javascript-if.js'][17]++;
  x();
}
_$jscoverage['javascript-if.js'][20]++;
if (x) {
  _$jscoverage['javascript-if.js'][21]++;
  x();
}
else {
  _$jscoverage['javascript-if.js'][23]++;
  if (x) {
    _$jscoverage['javascript-if.js'][24]++;
    x();
  }
  else {
    _$jscoverage['javascript-if.js'][27]++;
    x();
  }
}
