/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-number.js']) {
  _$jscoverage['javascript-number.js'] = [];
  _$jscoverage['javascript-number.js'][1] = 0;
  _$jscoverage['javascript-number.js'][2] = 0;
  _$jscoverage['javascript-number.js'][3] = 0;
}
_$jscoverage['javascript-number.js'][1]++;
x = 1;
_$jscoverage['javascript-number.js'][2]++;
y = 2;
_$jscoverage['javascript-number.js'][3]++;
z = 10.5;

// x = 1;
// y = 2;
// z = 10.5;
