/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-in.js']) {
  _$jscoverage['javascript-in.js'] = [];
  _$jscoverage['javascript-in.js'][1] = 0;
  _$jscoverage['javascript-in.js'][2] = 0;
  _$jscoverage['javascript-in.js'][3] = 0;
}
_$jscoverage['javascript-in.js'][1]++;
var x = {};
_$jscoverage['javascript-in.js'][2]++;
if ("a" in x) {
  _$jscoverage['javascript-in.js'][3]++;
  x = null;
}

// var x = {};
// if ('a' in x) {
//   x = null;
// }
