/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-switch.js']) {
  _$jscoverage['javascript-switch.js'] = [];
  _$jscoverage['javascript-switch.js'][1] = 0;
  _$jscoverage['javascript-switch.js'][3] = 0;
  _$jscoverage['javascript-switch.js'][4] = 0;
  _$jscoverage['javascript-switch.js'][6] = 0;
  _$jscoverage['javascript-switch.js'][7] = 0;
  _$jscoverage['javascript-switch.js'][8] = 0;
  _$jscoverage['javascript-switch.js'][10] = 0;
  _$jscoverage['javascript-switch.js'][11] = 0;
}
_$jscoverage['javascript-switch.js'][1]++;
switch (x) {
case x:
  _$jscoverage['javascript-switch.js'][3]++;
  x = 0;
  _$jscoverage['javascript-switch.js'][4]++;
  break;
case y:
  _$jscoverage['javascript-switch.js'][6]++;
  x = 0;
  _$jscoverage['javascript-switch.js'][7]++;
  y = 0;
  _$jscoverage['javascript-switch.js'][8]++;
  break;
default:
  _$jscoverage['javascript-switch.js'][10]++;
  x = 0;
  _$jscoverage['javascript-switch.js'][11]++;
  break;
}
