/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-assign.js']) {
  _$jscoverage['javascript-assign.js'] = [];
  _$jscoverage['javascript-assign.js'][1] = 0;
  _$jscoverage['javascript-assign.js'][2] = 0;
  _$jscoverage['javascript-assign.js'][3] = 0;
  _$jscoverage['javascript-assign.js'][4] = 0;
  _$jscoverage['javascript-assign.js'][5] = 0;
  _$jscoverage['javascript-assign.js'][6] = 0;
  _$jscoverage['javascript-assign.js'][7] = 0;
  _$jscoverage['javascript-assign.js'][8] = 0;
  _$jscoverage['javascript-assign.js'][9] = 0;
  _$jscoverage['javascript-assign.js'][10] = 0;
  _$jscoverage['javascript-assign.js'][11] = 0;
  _$jscoverage['javascript-assign.js'][12] = 0;
  _$jscoverage['javascript-assign.js'][13] = 0;
  _$jscoverage['javascript-assign.js'][14] = 0;
}
_$jscoverage['javascript-assign.js'].source = ["<span class=\"k\">var</span> x <span class=\"k\">=</span> <span class=\"s\">1</span><span class=\"k\">;</span>","<span class=\"k\">var</span> y <span class=\"k\">=</span> <span class=\"s\">1</span><span class=\"k\">;</span>","x <span class=\"k\">=</span> y<span class=\"k\">;</span>","x <span class=\"k\">+=</span> y<span class=\"k\">;</span>","x <span class=\"k\">-=</span> y<span class=\"k\">;</span>","x <span class=\"k\">*=</span> y<span class=\"k\">;</span>","x <span class=\"k\">%=</span> y<span class=\"k\">;</span>","x <span class=\"k\">&lt;&lt;=</span> y<span class=\"k\">;</span>","x <span class=\"k\">&gt;&gt;=</span> y<span class=\"k\">;</span>","x <span class=\"k\">&gt;&gt;&gt;=</span> y<span class=\"k\">;</span>","x <span class=\"k\">&amp;=</span> y<span class=\"k\">;</span>","x <span class=\"k\">|=</span> y<span class=\"k\">;</span>","x <span class=\"k\">^=</span> y<span class=\"k\">;</span>","x <span class=\"k\">/=</span> y<span class=\"k\">;</span>"];
_$jscoverage['javascript-assign.js'][1]++;
var x = 1;
_$jscoverage['javascript-assign.js'][2]++;
var y = 1;
_$jscoverage['javascript-assign.js'][3]++;
x = y;
_$jscoverage['javascript-assign.js'][4]++;
x += y;
_$jscoverage['javascript-assign.js'][5]++;
x -= y;
_$jscoverage['javascript-assign.js'][6]++;
x *= y;
_$jscoverage['javascript-assign.js'][7]++;
x %= y;
_$jscoverage['javascript-assign.js'][8]++;
x <<= y;
_$jscoverage['javascript-assign.js'][9]++;
x >>= y;
_$jscoverage['javascript-assign.js'][10]++;
x >>>= y;
_$jscoverage['javascript-assign.js'][11]++;
x &= y;
_$jscoverage['javascript-assign.js'][12]++;
x |= y;
_$jscoverage['javascript-assign.js'][13]++;
x ^= y;
_$jscoverage['javascript-assign.js'][14]++;
x /= y;
