/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['javascript-new.js']) {
  _$jscoverage['javascript-new.js'] = [];
  _$jscoverage['javascript-new.js'][1] = 0;
  _$jscoverage['javascript-new.js'][2] = 0;
  _$jscoverage['javascript-new.js'][3] = 0;
  _$jscoverage['javascript-new.js'][4] = 0;
}
_$jscoverage['javascript-new.js'][1]++;
function X() {
}
_$jscoverage['javascript-new.js'][2]++;
x = new X();
_$jscoverage['javascript-new.js'][3]++;
x = new X(1);
_$jscoverage['javascript-new.js'][4]++;
x = new X(1, 2);

// function X() {}
// x = new X();
// x = new X(1);
// x = new X(1, 2);
