/* automatically generated by JSCoverage - do not edit */
if (typeof top === 'object' && top !== null) {
  if (typeof top.opener === 'object' && top.opener !== null) {
    // this is a browser window that was opened from another window
    if (typeof top.opener._$jscoverage === 'object' && top.opener._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = top.opener._$jscoverage = {};
    }
  }
  else {
    // this is a browser window
    if (typeof top._$jscoverage === 'object' && top._$jscoverage !== null) {
      var _$jscoverage = top._$jscoverage;
    }
    else {
      var _$jscoverage = top._$jscoverage = {};
    }
  }
}
else {
  // no "top" - this is not a browser window
  if (typeof _$jscoverage === 'object' && _$jscoverage !== null) {
    // nothing to do
  }
  else {
    var _$jscoverage = {};
  }
}
if (! _$jscoverage['javascript-new.js']) {
  _$jscoverage['javascript-new.js'] = [];
  _$jscoverage['javascript-new.js'][1] = 0;
  _$jscoverage['javascript-new.js'][2] = 0;
  _$jscoverage['javascript-new.js'][3] = 0;
  _$jscoverage['javascript-new.js'][4] = 0;
  _$jscoverage['javascript-new.js'][5] = 0;
  _$jscoverage['javascript-new.js'][6] = 0;
  _$jscoverage['javascript-new.js'][7] = 0;
  _$jscoverage['javascript-new.js'][8] = 0;
  _$jscoverage['javascript-new.js'][9] = 0;
  _$jscoverage['javascript-new.js'][10] = 0;
  _$jscoverage['javascript-new.js'][11] = 0;
  _$jscoverage['javascript-new.js'][12] = 0;
  _$jscoverage['javascript-new.js'][13] = 0;
}
_$jscoverage['javascript-new.js'].source = ["<span class=\"k\">function</span> X<span class=\"k\">()</span> <span class=\"k\">{}</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> X<span class=\"k\">();</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> X<span class=\"k\">(</span><span class=\"s\">1</span><span class=\"k\">);</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> X<span class=\"k\">(</span><span class=\"s\">1</span><span class=\"k\">,</span> <span class=\"s\">2</span><span class=\"k\">);</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> X<span class=\"k\">;</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> <span class=\"k\">(</span>X<span class=\"k\">)();</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> <span class=\"k\">(</span>X<span class=\"k\">)(</span><span class=\"s\">1</span><span class=\"k\">);</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> <span class=\"k\">(</span>X<span class=\"k\">)(</span><span class=\"s\">1</span><span class=\"k\">,</span> <span class=\"s\">2</span><span class=\"k\">);</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> <span class=\"k\">(</span>X<span class=\"k\">);</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> <span class=\"k\">(</span>f<span class=\"k\">())();</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> <span class=\"k\">(</span>f<span class=\"k\">())(</span><span class=\"s\">1</span><span class=\"k\">);</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> <span class=\"k\">(</span>f<span class=\"k\">())(</span><span class=\"s\">1</span><span class=\"k\">,</span> <span class=\"s\">2</span><span class=\"k\">);</span>","x <span class=\"k\">=</span> <span class=\"k\">new</span> <span class=\"k\">(</span>f<span class=\"k\">());</span>"];
_$jscoverage['javascript-new.js'][1]++;
function X() {
}
_$jscoverage['javascript-new.js'][2]++;
x = new X();
_$jscoverage['javascript-new.js'][3]++;
x = new X(1);
_$jscoverage['javascript-new.js'][4]++;
x = new X(1, 2);
_$jscoverage['javascript-new.js'][5]++;
x = new X();
_$jscoverage['javascript-new.js'][6]++;
x = new X();
_$jscoverage['javascript-new.js'][7]++;
x = new X(1);
_$jscoverage['javascript-new.js'][8]++;
x = new X(1, 2);
_$jscoverage['javascript-new.js'][9]++;
x = new X();
_$jscoverage['javascript-new.js'][10]++;
x = new (f())();
_$jscoverage['javascript-new.js'][11]++;
x = new (f())(1);
_$jscoverage['javascript-new.js'][12]++;
x = new (f())(1, 2);
_$jscoverage['javascript-new.js'][13]++;
x = new (f())();
