/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['script.js']) {
  _$jscoverage['script.js'] = [];
  _$jscoverage['script.js'][1] = 0;
  _$jscoverage['script.js'][4] = 0;
  _$jscoverage['script.js'][5] = 0;
}
_$jscoverage['script.js'][1]++;
alert("hello");
_$jscoverage['script.js'][4]++;
if ("a" < "b" && "a" > "b") {
  _$jscoverage['script.js'][5]++;
  alert("?");
}
