/* automatically generated by JSCoverage - do not edit */
if (! top._$jscoverage) {
  top._$jscoverage = {};
}
var _$jscoverage = top._$jscoverage;
if (! _$jscoverage['@PREFIX@script.js']) {
  _$jscoverage['@PREFIX@script.js'] = [];
  _$jscoverage['@PREFIX@script.js'][1] = 0;
  _$jscoverage['@PREFIX@script.js'][4] = 0;
  _$jscoverage['@PREFIX@script.js'][5] = 0;
}
_$jscoverage['@PREFIX@script.js'][1]++;
alert("hello");
_$jscoverage['@PREFIX@script.js'][4]++;
if ("a" < "b" && "a" > "b") {
  _$jscoverage['@PREFIX@script.js'][5]++;
  alert("?");
}

// alert("hello");
// 
// // test formatting &lt; &gt; &amp;
// if ('a' < 'b' && 'a' > 'b') {
//   alert("?");
// }
